name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build
        run: npm run build
      - name: Test (with coverage)
        run: npm test
      - name: Generate SBOM
        run: npm run sbom
      - name: Package artifacts
        run: |
          mkdir -p release
          cp -r dist release/dist
          cp sbom.json release/
          if [ -d coverage ]; then cp -r coverage release/coverage; fi
          tar -czf release-artifacts.tgz -C release .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts.tgz
            sbom.json
          generate_release_notes: true
